### ISSUE TITLE
Firmware Error Encountered: I/O Error

### ISSUE THREAD

**Issue by shuk777** [tylerfanelli/snphost#1]
Detailed error:

```
ERROR: SNP_SET_EXT_CONFIG ioctl(2) failed
because: Firmware Error Encountered: I/O Error
because: I/O Error
because: Invalid argument (os error 22)
Error: SNP_SET_EXT_CONFIG ioctl(2) failed

Caused by:
    0: Firmware Error Encountered: I/O Error
    1: I/O Error
    2: Invalid argument (os error 22)
```

Does this mean that I use wrong cert format? Now I use pem for ark and ask, der for vcek.

**Comment by tylerfanelli** [comment]
@shuk777 The certificates should be in raw bytes.

**Comment by shuk777** [comment]
https://github.com/tylerfanelli/snphost/blob/cfc259ee4d6135237b60d93c0496df7c771fe336/src/certs/mod.rs#L74

Seems that this line should be `((size / 0x1000) + 1) * 0x1000`

**Comment by tylerfanelli** [comment]
@shuk777 Yes, you're right. Will fix.
